### ISSUE TITLE
Amazon Linux 2023 no tunnel interfaces

### ISSUE THREAD

**Issue by anwbtom** [aws-samples/aws-gateway-load-balancer-tunnel-handler#9]
Oddly enough this was working previously and when I started automating it seems to have broke.  
I cannot figure out why it's happening, to be sure I tested with main and the dev branch, but both seem to give the same result.  

The userdata used to prepare the instance for the NAT-tunnel is as follows:
``` bash
dnf groupinstall "Development Tools" -y
dnf install iptables-services cmake3 -y

systemctl enable iptables

cd /root
git clone https://github.com/aws-samples/aws-gateway-load-balancer-tunnel-handler.git
cd aws-gateway-load-balancer-tunnel-handler
cmake3 .
make

cat <<EOF > /root/create-nat.sh
#!/bin/bash

echo "==> Setting up two-armed NAT"
echo Mode is \$1, In Int is \$2, Out Int is \$3, ENI is \$4

iptables -F
iptables -t nat -F
iptables -t nat -A POSTROUTING -o ens5 -j MASQUERADE
iptables -A FORWARD -i \$2 -o ens5 -j ACCEPT

echo 1 > /proc/sys/net/ipv4/ip_forward
echo 0 > /proc/sys/net/ipv4/conf/all/rp_filter
echo 0 > /proc/sys/net/ipv4/conf/\$2/rp_filter
EOF
chmod 700 /root/create-nat.sh

cat <<EOF > /usr/lib/systemd/system/gwlbtun.service
[Unit]
Description=AWS GWLB Tunnel Handler

[Service]
ExecStart=/root/aws-gateway-load-balancer-tunnel-handler/gwlbtun -c /root/create-nat.sh -p 6081
Restart=always
RestartSec=5s
EOF

systemctl daemon-reload
systemctl enable --now --no-block gwlbtun.service
sleep 5
systemctl start gwlbtun.service

aws ec2 modify-instance-attribute --instance-id=$(ec2-metadata -i | awk '{print $2}') --no-source-dest-check
```

As can be seen the create-nat.sh is basically the one from the examples (and tested working previously) with the exception of the interface name since AL2023 add a `ens5` instead of a `eth0` interface.

Tried running the command with debug options on but the only thing the application prints out is this (and the health-check requests will continue forever as long as it runs):
```
/root/aws-gateway-load-balancer-tunnel-handler/gwlbtun -c /root/create-nat.sh -p 6081 -dx
2024-09-04 07:00:45.408: UDP receiver setting up on port 6081
2024-09-04 07:00:46.076: Processing a health check client for ::ffff:100.65.5.18
2024-09-04 07:00:46.076: GeneveHandler check running
2024-09-04 07:00:51.197: Processing a health check client for ::ffff:100.65.4.214
2024-09-04 07:00:51.197: GeneveHandler check running
```

When checking which interfaces exists through `ip addr` or something, it only gives the local loopback device + ens5, whilst I would expect 2 extra `gwi-*` interfaces to be present.  

Hope somebody can help me out debugging this problem, thanks in advance!

**Comment by grayaw** [comment]
At first glance, since you're not getting a log message showing the tunnels are being created, I would say your appliance hasn't received traffic yet. The interfaces get created on the first GENEVE packet (i.e. actual payload) being received. You have health checks appearing though - I'm assuming those are GWLB itself and not something you're probing yourself? 

Also note the -p 6081 has the health check running on TCP 6081, while GENEVE comes in on UDP 6081. This will work though.

I would perhaps check your security groups to ensure UDP 6081 is being allowed in.

**Comment by anwbtom** [comment]
Thank you so much for the response!
After trying some more stuff & things out, it turns out that my route-table wasn't properly updated and therefore initial traffic didn't start out.  Was under impression that the tunnel would be created after the first health-checks came in.  

Now playing around to get the securitygroups a bit more strict, but at least the base principal is working now :D
